name: CI-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@feature/MARP-3987-Improvements-How-to-handle-spelling-errors
    secrets:
      mvnArgs: |
       | sed -E "s|[0-9]. (WARNING) in ([^ ]*) \(at line ([0-9]+)\)(.*)|::\L\1 file=\2,line=\3::build issue\n\2@\3\4|g"\
       | sed -E "s|\[WARNING\] |::warning::|g"
